FROM python:3.9-slim-bullseye

# forces the stdout and stderr streams to be unbuffered
ENV PYTHONUNBUFFERED True

WORKDIR /cy-genai

COPY ./libs /cy-genai/libs
COPY ./certs /cy-genai/certs

COPY ./docker/cygenai-requirements.txt /cy-genai/cygenai-requirements.txt

# Install system dependencies
RUN apt-get update -y && apt-get install -y \
    telnet curl ffmpeg \
    && apt-get clean

# Install requirements
RUN pip install --no-cache-dir -r /cy-genai/cygenai-requirements.txt

# run listener
ENTRYPOINT ["python", "./libs/cygenai/cygenai_api_server.py"]